//! Embeds `migrations/NNNN_name.sql` into the binary.
//!
//! Generates `$OUT_DIR/migrations.rs` holding
//! `EMBEDDED: &[(&str /* file name */, &str /* sql */)]` sorted by version,
//! each entry an `include_str!` of the file. The build FAILS on a malformed
//! file name, a duplicate version, a directory or a stray file in
//! `migrations/`, so a bad migration set can never ship.

use std::{env, fmt::Write as _, fs, path::PathBuf, process::exit};

#[path = "src/db/migrate/filename.rs"]
mod filename;

const MIGRATIONS_DIR: &str = "migrations";

fn fail(message: &str) -> ! {
    // `cargo::error=` needs cargo 1.84; a plain stderr line plus a non-zero
    // exit works everywhere and is what cargo prints on failure.
    eprintln!("error: embedding migrations failed: {message}");
    exit(1);
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"),
    );
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let dir = manifest_dir.join(MIGRATIONS_DIR);

    // A directory is scanned recursively by cargo: adding, removing,
    // renaming or editing a migration reruns this script.
    println!("cargo:rerun-if-changed={MIGRATIONS_DIR}");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/db/migrate/filename.rs");

    let entries = match fs::read_dir(&dir) {
        Ok(entries) => entries,
        Err(e) => fail(&format!("cannot read {}: {e}", dir.display())),
    };

    let mut files: Vec<(u32, String)> = Vec::new();

    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(e) => fail(&format!("cannot list {}: {e}", dir.display())),
        };

        let Ok(file_name) = entry.file_name().into_string() else {
            fail(&format!(
                "non UTF-8 file name in {}: {:?}",
                dir.display(),
                entry.file_name()
            ));
        };

        // Editor / OS droppings (.DS_Store, .0001_x.sql.swp) are not
        // migrations.
        if file_name.starts_with('.') {
            continue;
        }

        let is_file =
            entry.file_type().map(|t| t.is_file()).unwrap_or(false);
        if !is_file {
            fail(&format!(
                "'{MIGRATIONS_DIR}/{file_name}' is not a regular file; the \
                 directory may only hold NNNN_name.sql files"
            ));
        }

        match filename::parse_filename(&file_name) {
            Ok((version, _)) => files.push((version, file_name)),
            Err(e) => fail(&e),
        }
    }

    if files.is_empty() {
        fail(&format!("no migrations found in {}", dir.display()));
    }

    files.sort();

    if let Err(e) = filename::check_unique(&files) {
        fail(&e);
    }

    let mut code = String::from(
        "/// `(file name, sql)` of every migration, sorted by version.\n\
         /// Generated by build.rs.\n\
         pub const EMBEDDED: &[(&str, &str)] = &[\n",
    );

    for (_, file_name) in &files {
        let path = dir.join(file_name);
        let path = path.to_str().unwrap_or_else(|| {
            fail(&format!("non UTF-8 path: {}", path.display()))
        });

        writeln!(code, "    ({file_name:?}, include_str!({path:?})),")
            .expect("write to string");
    }

    code.push_str("];\n");

    let out = out_dir.join("migrations.rs");
    if let Err(e) = fs::write(&out, code) {
        fail(&format!("cannot write {}: {e}", out.display()));
    }
}
