[package]
name = "evm-indexer"
version = "2.0.0"
license = "MIT"
edition = "2021"
repository = "https://github.com/eabz/evm-indexer"
description = "Scalable SQL indexer for EVM compatible blockchains"

[dependencies]
hypersync-client = "0.23.0"
log = "0.4"
simple_logger = { version = "5", default-features = false, features = [
    "colors",
] }
tokio = { version = "1", features = ["full"] }

[[bin]]
path = "bin/indexer.rs"
name = "indexer"
